### ISSUE TITLE
Unresolved reference: home

### ISSUE THREAD

**Issue by rehovicova** [WesleyElliott/Kubwa#8]
Hi, 

for some reason when I add this library to a gradle it fails to find `android.R.id.home`. Sounds strange but it is happening only when I add this library. When I remove it, it is working fine.

Any ideas how to solve it?

I am using Kotlin 1.2.10

Gradle 

```
apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-android-extensions'
apply plugin: 'kotlin-kapt'
apply plugin: 'realm-android'


def AAVersion = '4.4.0'
def supportVersion = "26.1.0"

android {
    compileSdkVersion 26
    defaultConfig {
        applicationId "com.xxx.xxx"
        minSdkVersion 19
        targetSdkVersion 26
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    dataBinding {
        enabled = true
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jre7:$kotlin_version"

    implementation "com.android.support:appcompat-v7:${supportVersion}"
    implementation "com.android.support:design:${supportVersion}"

    implementation 'android.arch.lifecycle:extensions:1.0.0'

    // Networking
    implementation('com.octo.android.robospice:robospice-retrofit:1.4.14') {
        exclude module: "commons-io"
    }
    implementation 'commons-io:commons-io:2.5'
    implementation 'com.squareup.okhttp3:okhttp:3.9.1'

    // Android Annotations
    implementation 'com.android.support:support-v4:26.1.0'
    kapt "com.android.databinding:compiler:3.0.1"
    kapt "org.androidannotations:androidannotations:$AAVersion"
    implementation "org.androidannotations:androidannotations-api:$AAVersion"

    // Parceler
    implementation 'org.parceler:parceler-api:1.1.7'
    kapt 'org.parceler:parceler:1.1.7'

    // Animations
    implementation 'com.daimajia.androidanimations:library:2.3@aar'

    // Image library
    implementation 'com.github.bumptech.glide:glide:4.2.0'
    kapt 'com.github.bumptech.glide:compiler:4.2.0'

    // Walk through
    implementation 'com.github.apl-devs:appintro:v4.2.2'

    // ZXing reader
    implementation 'com.google.zxing:core:3.3.0'
    implementation 'com.journeyapps:zxing-android-embedded:3.5.0'

    // Skeleton view
    implementation 'com.ethanhua:skeleton:1.0.1'
    implementation 'io.supercharge:shimmerlayout:1.0.2'

    // Validations
    implementation 'com.wesleyelliott:kubwa-annotations:1.0.1'
    kapt 'com.wesleyelliott:kubwa-compiler:1.0.1'

    // Multidex
    implementation 'com.android.support:multidex:1.0.1'

}
```

android.R.id.home usage
```
override fun onOptionsItemSelected(item: MenuItem): Boolean {
        when (item.itemId) {
            android.R.id.home -> {
                ...
            }
        }

        return super.onOptionsItemSelected(item)
    }
```

**Comment by WesleyElliott** [comment]
Hi,
That is very strange - I'll have to look into it. I've unfortunately not tested this library with Kotlin, but that shouldn't make much of a difference.

**Comment by rehovicova** [comment]
I will try to make a simple kotlin project and check if it is not a kotlin issue.

**Comment by WesleyElliott** [comment]
Thanks for the help! 
The library does use an outdated version of android (that didn't have `android.R.id.home`), so I'll look into updating that, as it may well solve the issue.

**Comment by rehovicova** [comment]
Great! Please let me know when update will be ready :)

**Comment by WesleyElliott** [comment]
@rehovicova , I've pushed some fixes (library updates etc), so all should be good on the `1.1.1` release.
Please let me know if it works, and I'll close the issue :)

**Comment by rehovicova** [comment]
Now I am getting a different exception, the id should be fixed though.

```
java.lang.IllegalStateException: failed to analyze: java.lang.NoClassDefFoundError: com/squareup/javapoet/TypeSpec
	at org.jetbrains.kotlin.analyzer.AnalysisResult.throwIfError(AnalysisResult.kt:57)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules(KotlinToJVMBytecodeCompiler.kt:137)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:158)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:61)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.java:107)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.java:51)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:92)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl$compile$1$2.invoke(CompileServiceImpl.kt:386)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl$compile$1$2.invoke(CompileServiceImpl.kt:96)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl$doCompile$$inlined$ifAlive$lambda$2.invoke(CompileServiceImpl.kt:892)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl$doCompile$$inlined$ifAlive$lambda$2.invoke(CompileServiceImpl.kt:96)
	at org.jetbrains.kotlin.daemon.common.DummyProfiler.withMeasure(PerfUtils.kt:137)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl.checkedCompile(CompileServiceImpl.kt:919)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl.doCompile(CompileServiceImpl.kt:891)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl.compile(CompileServiceImpl.kt:385)
	at sun.reflect.GeneratedMethodAccessor111.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:346)
	at sun.rmi.transport.Transport$1.run(Transport.java:200)
	at sun.rmi.transport.Transport$1.run(Transport.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:568)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:826)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:683)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:682)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoClassDefFoundError: com/squareup/javapoet/TypeSpec
	at com.wesleyelliott.kubwa.CodeGenerator.generateClass(CodeGenerator.java:46)
	at com.wesleyelliott.kubwa.KubwaCompiler.generate(KubwaCompiler.java:378)
	at com.wesleyelliott.kubwa.KubwaCompiler.process(KubwaCompiler.java:140)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:794)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:705)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1800(JavacProcessingEnvironment.java:91)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1035)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1176)
	at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1170)
	at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1068)
	at org.jetbrains.kotlin.kapt3.AnnotationProcessingKt.doAnnotationProcessing(annotationProcessing.kt:73)
	at org.jetbrains.kotlin.kapt3.AnnotationProcessingKt.doAnnotationProcessing$default(annotationProcessing.kt:42)
	at org.jetbrains.kotlin.kapt3.AbstractKapt3Extension.runAnnotationProcessing(Kapt3Extension.kt:205)
	at org.jetbrains.kotlin.kapt3.AbstractKapt3Extension.analysisCompleted(Kapt3Extension.kt:166)
	at org.jetbrains.kotlin.kapt3.ClasspathBasedKapt3Extension.analysisCompleted(Kapt3Extension.kt:82)
	at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM$analyzeFilesWithJavaIntegration$2.invoke(TopDownAnalyzerFacadeForJVM.kt:96)
	at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration(TopDownAnalyzerFacadeForJVM.kt:106)
	at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration$default(TopDownAnalyzerFacadeForJVM.kt:83)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler$analyze$1.invoke(KotlinToJVMBytecodeCompiler.kt:376)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler$analyze$1.invoke(KotlinToJVMBytecodeCompiler.kt:67)
	at org.jetbrains.kotlin.cli.common.messages.AnalyzerWithCompilerReport.analyzeAndReport(AnalyzerWithCompilerReport.kt:96)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.analyze(KotlinToJVMBytecodeCompiler.kt:367)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules(KotlinToJVMBytecodeCompiler.kt:132)
	... 29 more
Caused by: java.lang.ClassNotFoundException: com.squareup.javapoet.TypeSpec
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 52 more
```

**Comment by WesleyElliott** [comment]
Thanks for the feedback. Seems the annotation processor is getting confused between java and kotlin. Either use `annotationProcessor` for this library (instead of `kapt`), or force the javapoet library to use `kapt` by adding an extra dependancy:

`kapt 'com.squareup:javapoet:1.10.0'`

**Comment by rehovicova** [comment]
Thanks for explanation, I wasn't exactly sure why I was getting that.

Using `annotationProcessor` is not generating `SomeClass*Validator*`.
`kapt 'com.squareup:javapoet:1.10.0'` solved the issue.

Thank you for help :)
